# This file runs when DFHack is initialized, when Dwarf Fortress is first
# started, before any world or save data is loaded.
#
# You can extend or override DFHack's default configuration by adding commands
# to this file.
#
# End a line with a backslash to make it continue to the next line. The \ is
# deleted for the final command. Multiline commands are ONLY supported for
# scripts like dfhack.init. You cannot do multiline command manually on the
# DFHack console. You cannot extend a commented line. You can comment out the
# extension of a line.
